version: '3.8'
services:
  app:
    container_name: poke_app
    build: .
    image: waomi/poke:latest
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - ftp
      - redis
  postgres:
    container_name: poke_db
    image: postgres:latest
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  ftp:
    container_name: poke_ftp
    image: delfer/alpine-ftp-server
    restart: always
    expose:
      - 21
    environment:
      - "USERS=${FTP_USER}|${FTP_PASSWORD}|/ftp/ftp"
  redis:
    container_name: poke_cache
    image: redis:7.0.9-alpine
    restart: unless-stopped
    command: redis-server --port "${CACHE_REDIS_PORT}"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: