# Generated by Django 4.2.6 on 2023-10-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='round_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]